CREATE TABLE <table-name>_mc (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    collection_name VARCHAR(255) NOT NULL,
    collection_mappings LONGTEXT NOT NULL,
    user_created INT UNSIGNED DEFAULT 0,
    user_updated INT UNSIGNED DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY(collection_name)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;