CREATE TABLE <table-name> (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    source VARCHAR(512) NOT NULL,
    destination VARCHAR(512) NOT NULL,
    user_created INT UNSIGNED DEFAULT 0,
    user_updated INT UNSIGNED DEFAULT 0,
    date_start DATETIME NULL,
    date_end DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;