CREATE TABLE <table-name>_log (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    redirect_id INT UNSIGNED NOT NULL,
    source_url VARCHAR(512) NOT NULL,
    destination_url VARCHAR(512) NOT NULL,
    redirected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    agent_string VARCHAR(255) NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;