CREATE TABLE <table-name>_vi (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    var_name VARCHAR(255) NOT NULL,
    var_value VARCHAR(255) NOT NULL,
    user_created INT UNSIGNED DEFAULT 0,
    user_updated INT UNSIGNED DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY(var_name)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;