CREATE TABLE <table-name>_pjr (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    pjr_name VARCHAR(255) NOT NULL,
    pjr_value VARCHAR(255) NOT NULL,
    user_created INT UNSIGNED DEFAULT 0,
    user_updated INT UNSIGNED DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY(pjr_name)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;